DROP TABLE IF EXISTS round;

DROP TABLE IF EXISTS tx_request;

DROP TABLE IF EXISTS receiver;

DROP TABLE IF EXISTS tx;

DROP TABLE IF EXISTS vtxo;

DROP TABLE IF EXISTS entity_vtxo;

DROP TABLE IF EXISTS entity;

DROP TABLE IF EXISTS note;