ALTER TABLE tx ADD COLUMN tree_level INTEGER;
ALTER TABLE tx ADD COLUMN parent_txid TEXT;
ALTER TABLE tx ADD COLUMN is_leaf BOOLEAN;

ALTER TABLE tx DROP COLUMN children TEXT;

DROP VIEW IF EXISTS round_tx_vw;
CREATE VIEW IF NOT EXISTS round_tx_vw AS
SELECT tx.*
FROM round
LEFT OUTER JOIN tx
ON round.id=tx.round_id;