DROP TABLE IF EXISTS round;

DROP TABLE IF EXISTS tx_request;

DROP TABLE IF EXISTS receiver;

DROP TABLE IF EXISTS tx;

DROP TABLE IF EXISTS vtxo;

DROP TABLE IF EXISTS entity_vtxo;

DROP TABLE IF EXISTS entity;

DROP TABLE IF EXISTS note;

DROP TABLE IF EXISTS market_hours;

DROP INDEX IF EXISTS idx_round_txid;

DROP VIEW IF EXISTS entity_vw;

DROP VIEW IF EXISTS round_request_vw;

DROP VIEW IF EXISTS round_tx_vw;

DROP VIEW IF EXISTS request_receiver_vw;

DROP VIEW IF EXISTS request_vtxo_vw;