#!/bin/bash

set -e

PARENT_PATH=$(dirname $(
    cd $(dirname $0)
    pwd -P
))

declare -a OS=("darwin" "linux")
declare -a ARCH=("amd64" "arm64")

pushd $PARENT_PATH

for os in "${OS[@]}"; do
  for arch in "${ARCH[@]}"; do
    GOOS=$os GOARCH=$arch ./scripts/build $1
  done
done

popd