#!/bin/bash

set -e

PARENT_PATH=$(dirname $(
	cd $(dirname $0)
	pwd -P
))

if [[ -z $GOOS ]]; then
	GOOS=$(eval "go env GOOS")
fi

if [[ -z $GOARCH ]]; then
	GOARCH=$(eval "go env GOARCH")
fi

echo "Building for $GOOS $GOARCH"

pushd $PARENT_PATH
mkdir -p build


if [[ $1 == *-faucet* ]]; then
    GO111MODULE=on go build -ldflags="-s -w" -o build/ark-cli-$GOOS-$GOARCH .
else
	FILES=$(find . -type f -name '*.go' ! -name 'faucet.go')
    GO111MODULE=on go build -ldflags="-s -w" -o build/ark-cli-$GOOS-$GOARCH $FILES
fi

popd
