// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1BatchTreeEvent v1 batch tree event
//
// swagger:model v1BatchTreeEvent
type V1BatchTreeEvent struct {

	// batch index
	BatchIndex int32 `json:"batchIndex,omitempty"`

	// output index -> child txid
	Children map[string]string `json:"children,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// topic
	Topic []string `json:"topic"`

	// tx
	Tx string `json:"tx,omitempty"`

	// txid
	Txid string `json:"txid,omitempty"`
}

// Validate validates this v1 batch tree event
func (m *V1BatchTreeEvent) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 batch tree event based on context it is used
func (m *V1BatchTreeEvent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1BatchTreeEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1BatchTreeEvent) UnmarshalBinary(b []byte) error {
	var res V1BatchTreeEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
