// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V1CreatePaymentResponse v1 create payment response
// swagger:model v1CreatePaymentResponse
type V1CreatePaymentResponse struct {

	// signed only by the ASP
	SignedRedeemTx string `json:"signedRedeemTx,omitempty"`

	// usigned unconditional forfeit txs
	UsignedUnconditionalForfeitTxs []string `json:"usignedUnconditionalForfeitTxs"`
}

// Validate validates this v1 create payment response
func (m *V1CreatePaymentResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1CreatePaymentResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1CreatePaymentResponse) UnmarshalBinary(b []byte) error {
	var res V1CreatePaymentResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
