// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1DescriptorInput v1 descriptor input
//
// swagger:model v1DescriptorInput
type V1DescriptorInput struct {

	// descriptor
	Descriptor string `json:"descriptor,omitempty"`

	// txid
	Txid string `json:"txid,omitempty"`

	// vout
	Vout int64 `json:"vout,omitempty"`
}

// Validate validates this v1 descriptor input
func (m *V1DescriptorInput) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 descriptor input based on context it is used
func (m *V1DescriptorInput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1DescriptorInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1DescriptorInput) UnmarshalBinary(b []byte) error {
	var res V1DescriptorInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
