// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1DeleteIntentResponse v1 delete intent response
//
// swagger:model v1DeleteIntentResponse
type V1DeleteIntentResponse interface{}
