// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1FinalizeOffchainTxRequest v1 finalize offchain tx request
//
// swagger:model v1FinalizeOffchainTxRequest
type V1FinalizeOffchainTxRequest struct {

	// checkpoint txs
	CheckpointTxs []string `json:"checkpointTxs"`

	// txid
	Txid string `json:"txid,omitempty"`
}

// Validate validates this v1 finalize offchain tx request
func (m *V1FinalizeOffchainTxRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 finalize offchain tx request based on context it is used
func (m *V1FinalizeOffchainTxRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1FinalizeOffchainTxRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1FinalizeOffchainTxRequest) UnmarshalBinary(b []byte) error {
	var res V1FinalizeOffchainTxRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
