// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1FinalizeOffchainTxResponse v1 finalize offchain tx response
//
// swagger:model v1FinalizeOffchainTxResponse
type V1FinalizeOffchainTxResponse interface{}
