// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1Input v1 input
//
// swagger:model v1Input
type V1Input struct {

	// descriptor
	Descriptor string `json:"descriptor,omitempty"`

	// outpoint
	Outpoint *V1Outpoint `json:"outpoint,omitempty"`

	// tapscripts
	Tapscripts *V1Tapscripts `json:"tapscripts,omitempty"`
}

// Validate validates this v1 input
func (m *V1Input) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOutpoint(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTapscripts(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1Input) validateOutpoint(formats strfmt.Registry) error {
	if swag.IsZero(m.Outpoint) { // not required
		return nil
	}

	if m.Outpoint != nil {
		if err := m.Outpoint.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("outpoint")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("outpoint")
			}
			return err
		}
	}

	return nil
}

func (m *V1Input) validateTapscripts(formats strfmt.Registry) error {
	if swag.IsZero(m.Tapscripts) { // not required
		return nil
	}

	if m.Tapscripts != nil {
		if err := m.Tapscripts.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tapscripts")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tapscripts")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 input based on the context it is used
func (m *V1Input) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOutpoint(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTapscripts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1Input) contextValidateOutpoint(ctx context.Context, formats strfmt.Registry) error {

	if m.Outpoint != nil {

		if swag.IsZero(m.Outpoint) { // not required
			return nil
		}

		if err := m.Outpoint.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("outpoint")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("outpoint")
			}
			return err
		}
	}

	return nil
}

func (m *V1Input) contextValidateTapscripts(ctx context.Context, formats strfmt.Registry) error {

	if m.Tapscripts != nil {

		if swag.IsZero(m.Tapscripts) { // not required
			return nil
		}

		if err := m.Tapscripts.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tapscripts")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tapscripts")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1Input) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1Input) UnmarshalBinary(b []byte) error {
	var res V1Input
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
