// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1IndexerOutpoint v1 indexer outpoint
//
// swagger:model v1IndexerOutpoint
type V1IndexerOutpoint struct {

	// txid
	Txid string `json:"txid,omitempty"`

	// vout
	Vout int64 `json:"vout,omitempty"`
}

// Validate validates this v1 indexer outpoint
func (m *V1IndexerOutpoint) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 indexer outpoint based on context it is used
func (m *V1IndexerOutpoint) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1IndexerOutpoint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1IndexerOutpoint) UnmarshalBinary(b []byte) error {
	var res V1IndexerOutpoint
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
