// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V1Payment v1 payment
// swagger:model v1Payment
type V1Payment struct {

	// amount
	Amount int64 `json:"amount,omitempty"`

	// pending
	Pending bool `json:"pending,omitempty"`

	// pubkey
	Pubkey string `json:"pubkey,omitempty"`

	// spent
	Spent bool `json:"spent,omitempty"`

	// txid
	Txid string `json:"txid,omitempty"`

	// vout
	Vout int64 `json:"vout,omitempty"`
}

// Validate validates this v1 payment
func (m *V1Payment) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1Payment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1Payment) UnmarshalBinary(b []byte) error {
	var res V1Payment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
