// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1RoundFailed v1 round failed
//
// swagger:model v1RoundFailed
type V1RoundFailed struct {

	// id
	ID string `json:"id,omitempty"`

	// reason
	Reason string `json:"reason,omitempty"`
}

// Validate validates this v1 round failed
func (m *V1RoundFailed) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 round failed based on context it is used
func (m *V1RoundFailed) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1RoundFailed) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1RoundFailed) UnmarshalBinary(b []byte) error {
	var res V1RoundFailed
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
