// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1RoundSigningEvent v1 round signing event
//
// swagger:model v1RoundSigningEvent
type V1RoundSigningEvent struct {

	// cosigners pubkeys
	CosignersPubkeys []string `json:"cosignersPubkeys"`

	// id
	ID string `json:"id,omitempty"`

	// unsigned round tx
	UnsignedRoundTx string `json:"unsignedRoundTx,omitempty"`
}

// Validate validates this v1 round signing event
func (m *V1RoundSigningEvent) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 round signing event based on context it is used
func (m *V1RoundSigningEvent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1RoundSigningEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1RoundSigningEvent) UnmarshalBinary(b []byte) error {
	var res V1RoundSigningEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
