// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1Round v1 round
//
// swagger:model v1Round
type V1Round struct {

	// connectors
	Connectors []*V1TxGraphChunk `json:"connectors"`

	// end
	End string `json:"end,omitempty"`

	// forfeit txs
	ForfeitTxs []string `json:"forfeitTxs"`

	// id
	ID string `json:"id,omitempty"`

	// round tx
	RoundTx string `json:"roundTx,omitempty"`

	// stage
	Stage *V1RoundStage `json:"stage,omitempty"`

	// start
	Start string `json:"start,omitempty"`

	// vtxo tree
	VtxoTree []*V1TxGraphChunk `json:"vtxoTree"`
}

// Validate validates this v1 round
func (m *V1Round) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConnectors(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVtxoTree(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1Round) validateConnectors(formats strfmt.Registry) error {
	if swag.IsZero(m.Connectors) { // not required
		return nil
	}

	for i := 0; i < len(m.Connectors); i++ {
		if swag.IsZero(m.Connectors[i]) { // not required
			continue
		}

		if m.Connectors[i] != nil {
			if err := m.Connectors[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("connectors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("connectors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1Round) validateStage(formats strfmt.Registry) error {
	if swag.IsZero(m.Stage) { // not required
		return nil
	}

	if m.Stage != nil {
		if err := m.Stage.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stage")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stage")
			}
			return err
		}
	}

	return nil
}

func (m *V1Round) validateVtxoTree(formats strfmt.Registry) error {
	if swag.IsZero(m.VtxoTree) { // not required
		return nil
	}

	for i := 0; i < len(m.VtxoTree); i++ {
		if swag.IsZero(m.VtxoTree[i]) { // not required
			continue
		}

		if m.VtxoTree[i] != nil {
			if err := m.VtxoTree[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("vtxoTree" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("vtxoTree" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v1 round based on the context it is used
func (m *V1Round) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateConnectors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVtxoTree(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1Round) contextValidateConnectors(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Connectors); i++ {

		if m.Connectors[i] != nil {

			if swag.IsZero(m.Connectors[i]) { // not required
				return nil
			}

			if err := m.Connectors[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("connectors" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("connectors" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1Round) contextValidateStage(ctx context.Context, formats strfmt.Registry) error {

	if m.Stage != nil {

		if swag.IsZero(m.Stage) { // not required
			return nil
		}

		if err := m.Stage.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("stage")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("stage")
			}
			return err
		}
	}

	return nil
}

func (m *V1Round) contextValidateVtxoTree(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.VtxoTree); i++ {

		if m.VtxoTree[i] != nil {

			if swag.IsZero(m.VtxoTree[i]) { // not required
				return nil
			}

			if err := m.VtxoTree[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("vtxoTree" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("vtxoTree" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1Round) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1Round) UnmarshalBinary(b []byte) error {
	var res V1Round
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
