// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V1RegisterPaymentResponse v1 register payment response
// swagger:model v1RegisterPaymentResponse
type V1RegisterPaymentResponse struct {

	// Mocks wabisabi's credentials.
	ID string `json:"id,omitempty"`
}

// Validate validates this v1 register payment response
func (m *V1RegisterPaymentResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1RegisterPaymentResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1RegisterPaymentResponse) UnmarshalBinary(b []byte) error {
	var res V1RegisterPaymentResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
