// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1RoundFinalizationEvent v1 round finalization event
//
// swagger:model v1RoundFinalizationEvent
type V1RoundFinalizationEvent struct {

	// connectors
	Connectors *V1Tree `json:"connectors,omitempty"`

	// vtxo outpoint encoded as string -> connector outpoint
	ConnectorsIndex map[string]V1Outpoint `json:"connectorsIndex,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// min relay fee rate
	MinRelayFeeRate string `json:"minRelayFeeRate,omitempty"`

	// round tx
	RoundTx string `json:"roundTx,omitempty"`

	// vtxo tree
	VtxoTree *V1Tree `json:"vtxoTree,omitempty"`
}

// Validate validates this v1 round finalization event
func (m *V1RoundFinalizationEvent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConnectors(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConnectorsIndex(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVtxoTree(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1RoundFinalizationEvent) validateConnectors(formats strfmt.Registry) error {
	if swag.IsZero(m.Connectors) { // not required
		return nil
	}

	if m.Connectors != nil {
		if err := m.Connectors.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("connectors")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("connectors")
			}
			return err
		}
	}

	return nil
}

func (m *V1RoundFinalizationEvent) validateConnectorsIndex(formats strfmt.Registry) error {
	if swag.IsZero(m.ConnectorsIndex) { // not required
		return nil
	}

	for k := range m.ConnectorsIndex {

		if err := validate.Required("connectorsIndex"+"."+k, "body", m.ConnectorsIndex[k]); err != nil {
			return err
		}
		if val, ok := m.ConnectorsIndex[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("connectorsIndex" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("connectorsIndex" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1RoundFinalizationEvent) validateVtxoTree(formats strfmt.Registry) error {
	if swag.IsZero(m.VtxoTree) { // not required
		return nil
	}

	if m.VtxoTree != nil {
		if err := m.VtxoTree.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("vtxoTree")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("vtxoTree")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 round finalization event based on the context it is used
func (m *V1RoundFinalizationEvent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateConnectors(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateConnectorsIndex(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVtxoTree(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1RoundFinalizationEvent) contextValidateConnectors(ctx context.Context, formats strfmt.Registry) error {

	if m.Connectors != nil {

		if swag.IsZero(m.Connectors) { // not required
			return nil
		}

		if err := m.Connectors.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("connectors")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("connectors")
			}
			return err
		}
	}

	return nil
}

func (m *V1RoundFinalizationEvent) contextValidateConnectorsIndex(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.ConnectorsIndex {

		if val, ok := m.ConnectorsIndex[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *V1RoundFinalizationEvent) contextValidateVtxoTree(ctx context.Context, formats strfmt.Registry) error {

	if m.VtxoTree != nil {

		if swag.IsZero(m.VtxoTree) { // not required
			return nil
		}

		if err := m.VtxoTree.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("vtxoTree")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("vtxoTree")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1RoundFinalizationEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1RoundFinalizationEvent) UnmarshalBinary(b []byte) error {
	var res V1RoundFinalizationEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
