// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1RegisterInputsForNextRoundResponse v1 register inputs for next round response
//
// swagger:model v1RegisterInputsForNextRoundResponse
type V1RegisterInputsForNextRoundResponse struct {

	// request Id
	RequestID string `json:"requestId,omitempty"`
}

// Validate validates this v1 register inputs for next round response
func (m *V1RegisterInputsForNextRoundResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 register inputs for next round response based on context it is used
func (m *V1RegisterInputsForNextRoundResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1RegisterInputsForNextRoundResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1RegisterInputsForNextRoundResponse) UnmarshalBinary(b []byte) error {
	var res V1RegisterInputsForNextRoundResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
