// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1SubmitSignedForfeitTransactionsRequest v1 submit signed forfeit transactions request
//
// swagger:model v1SubmitSignedForfeitTransactionsRequest
type V1SubmitSignedForfeitTransactionsRequest struct {

	// Forfeit txs signed by the user.
	SignedForfeitTxs []string `json:"signedForfeitTxs"`

	// If payment has boarding input, the user must sign the associated inputs.
	SignedRoundTx string `json:"signedRoundTx,omitempty"`
}

// Validate validates this v1 submit signed forfeit transactions request
func (m *V1SubmitSignedForfeitTransactionsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 submit signed forfeit transactions request based on context it is used
func (m *V1SubmitSignedForfeitTransactionsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1SubmitSignedForfeitTransactionsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1SubmitSignedForfeitTransactionsRequest) UnmarshalBinary(b []byte) error {
	var res V1SubmitSignedForfeitTransactionsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
