// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1SubmitTxResponse v1 submit tx response
//
// swagger:model v1SubmitTxResponse
type V1SubmitTxResponse struct {

	// ark txid
	ArkTxid string `json:"arkTxid,omitempty"`

	// final ark tx
	FinalArkTx string `json:"finalArkTx,omitempty"`

	// signed checkpoint txs
	SignedCheckpointTxs []string `json:"signedCheckpointTxs"`
}

// Validate validates this v1 submit tx response
func (m *V1SubmitTxResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 submit tx response based on context it is used
func (m *V1SubmitTxResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1SubmitTxResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1SubmitTxResponse) UnmarshalBinary(b []byte) error {
	var res V1SubmitTxResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
