// Code generated by go-swagger; DO NOT EDIT.

package ark_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ark-network/ark/common/client-sdk/rest/service/models"
)

// ArkServiceTrustedOnboardingReader is a Reader for the ArkServiceTrustedOnboarding structure.
type ArkServiceTrustedOnboardingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ArkServiceTrustedOnboardingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewArkServiceTrustedOnboardingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewArkServiceTrustedOnboardingDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewArkServiceTrustedOnboardingOK creates a ArkServiceTrustedOnboardingOK with default headers values
func NewArkServiceTrustedOnboardingOK() *ArkServiceTrustedOnboardingOK {
	return &ArkServiceTrustedOnboardingOK{}
}

/*ArkServiceTrustedOnboardingOK handles this case with default header values.

A successful response.
*/
type ArkServiceTrustedOnboardingOK struct {
	Payload *models.V1TrustedOnboardingResponse
}

func (o *ArkServiceTrustedOnboardingOK) Error() string {
	return fmt.Sprintf("[POST /v1/onboard/address][%d] arkServiceTrustedOnboardingOK  %+v", 200, o.Payload)
}

func (o *ArkServiceTrustedOnboardingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1TrustedOnboardingResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewArkServiceTrustedOnboardingDefault creates a ArkServiceTrustedOnboardingDefault with default headers values
func NewArkServiceTrustedOnboardingDefault(code int) *ArkServiceTrustedOnboardingDefault {
	return &ArkServiceTrustedOnboardingDefault{
		_statusCode: code,
	}
}

/*ArkServiceTrustedOnboardingDefault handles this case with default header values.

An unexpected error response.
*/
type ArkServiceTrustedOnboardingDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the ark service trusted onboarding default response
func (o *ArkServiceTrustedOnboardingDefault) Code() int {
	return o._statusCode
}

func (o *ArkServiceTrustedOnboardingDefault) Error() string {
	return fmt.Sprintf("[POST /v1/onboard/address][%d] ArkService_TrustedOnboarding default  %+v", o._statusCode, o.Payload)
}

func (o *ArkServiceTrustedOnboardingDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
