// Code generated by go-swagger; DO NOT EDIT.

package indexer_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewIndexerServiceGetConnectorsParams creates a new IndexerServiceGetConnectorsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIndexerServiceGetConnectorsParams() *IndexerServiceGetConnectorsParams {
	return &IndexerServiceGetConnectorsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewIndexerServiceGetConnectorsParamsWithTimeout creates a new IndexerServiceGetConnectorsParams object
// with the ability to set a timeout on a request.
func NewIndexerServiceGetConnectorsParamsWithTimeout(timeout time.Duration) *IndexerServiceGetConnectorsParams {
	return &IndexerServiceGetConnectorsParams{
		timeout: timeout,
	}
}

// NewIndexerServiceGetConnectorsParamsWithContext creates a new IndexerServiceGetConnectorsParams object
// with the ability to set a context for a request.
func NewIndexerServiceGetConnectorsParamsWithContext(ctx context.Context) *IndexerServiceGetConnectorsParams {
	return &IndexerServiceGetConnectorsParams{
		Context: ctx,
	}
}

// NewIndexerServiceGetConnectorsParamsWithHTTPClient creates a new IndexerServiceGetConnectorsParams object
// with the ability to set a custom HTTPClient for a request.
func NewIndexerServiceGetConnectorsParamsWithHTTPClient(client *http.Client) *IndexerServiceGetConnectorsParams {
	return &IndexerServiceGetConnectorsParams{
		HTTPClient: client,
	}
}

/*
IndexerServiceGetConnectorsParams contains all the parameters to send to the API endpoint

	for the indexer service get connectors operation.

	Typically these are written to a http.Request.
*/
type IndexerServiceGetConnectorsParams struct {

	// BatchOutpointTxid.
	BatchOutpointTxid string

	// BatchOutpointVout.
	//
	// Format: int64
	BatchOutpointVout int64

	// PageIndex.
	//
	// Format: int32
	PageIndex *int32

	// PageSize.
	//
	// Format: int32
	PageSize *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the indexer service get connectors params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IndexerServiceGetConnectorsParams) WithDefaults() *IndexerServiceGetConnectorsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the indexer service get connectors params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IndexerServiceGetConnectorsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the indexer service get connectors params
func (o *IndexerServiceGetConnectorsParams) WithTimeout(timeout time.Duration) *IndexerServiceGetConnectorsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the indexer service get connectors params
func (o *IndexerServiceGetConnectorsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the indexer service get connectors params
func (o *IndexerServiceGetConnectorsParams) WithContext(ctx context.Context) *IndexerServiceGetConnectorsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the indexer service get connectors params
func (o *IndexerServiceGetConnectorsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the indexer service get connectors params
func (o *IndexerServiceGetConnectorsParams) WithHTTPClient(client *http.Client) *IndexerServiceGetConnectorsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the indexer service get connectors params
func (o *IndexerServiceGetConnectorsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBatchOutpointTxid adds the batchOutpointTxid to the indexer service get connectors params
func (o *IndexerServiceGetConnectorsParams) WithBatchOutpointTxid(batchOutpointTxid string) *IndexerServiceGetConnectorsParams {
	o.SetBatchOutpointTxid(batchOutpointTxid)
	return o
}

// SetBatchOutpointTxid adds the batchOutpointTxid to the indexer service get connectors params
func (o *IndexerServiceGetConnectorsParams) SetBatchOutpointTxid(batchOutpointTxid string) {
	o.BatchOutpointTxid = batchOutpointTxid
}

// WithBatchOutpointVout adds the batchOutpointVout to the indexer service get connectors params
func (o *IndexerServiceGetConnectorsParams) WithBatchOutpointVout(batchOutpointVout int64) *IndexerServiceGetConnectorsParams {
	o.SetBatchOutpointVout(batchOutpointVout)
	return o
}

// SetBatchOutpointVout adds the batchOutpointVout to the indexer service get connectors params
func (o *IndexerServiceGetConnectorsParams) SetBatchOutpointVout(batchOutpointVout int64) {
	o.BatchOutpointVout = batchOutpointVout
}

// WithPageIndex adds the pageIndex to the indexer service get connectors params
func (o *IndexerServiceGetConnectorsParams) WithPageIndex(pageIndex *int32) *IndexerServiceGetConnectorsParams {
	o.SetPageIndex(pageIndex)
	return o
}

// SetPageIndex adds the pageIndex to the indexer service get connectors params
func (o *IndexerServiceGetConnectorsParams) SetPageIndex(pageIndex *int32) {
	o.PageIndex = pageIndex
}

// WithPageSize adds the pageSize to the indexer service get connectors params
func (o *IndexerServiceGetConnectorsParams) WithPageSize(pageSize *int32) *IndexerServiceGetConnectorsParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the indexer service get connectors params
func (o *IndexerServiceGetConnectorsParams) SetPageSize(pageSize *int32) {
	o.PageSize = pageSize
}

// WriteToRequest writes these params to a swagger request
func (o *IndexerServiceGetConnectorsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param batchOutpoint.txid
	if err := r.SetPathParam("batchOutpoint.txid", o.BatchOutpointTxid); err != nil {
		return err
	}

	// path param batchOutpoint.vout
	if err := r.SetPathParam("batchOutpoint.vout", swag.FormatInt64(o.BatchOutpointVout)); err != nil {
		return err
	}

	if o.PageIndex != nil {

		// query param page.index
		var qrPageIndex int32

		if o.PageIndex != nil {
			qrPageIndex = *o.PageIndex
		}
		qPageIndex := swag.FormatInt32(qrPageIndex)
		if qPageIndex != "" {

			if err := r.SetQueryParam("page.index", qPageIndex); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param page.size
		var qrPageSize int32

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt32(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("page.size", qPageSize); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
