// Code generated by go-swagger; DO NOT EDIT.

package indexer_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewIndexerServiceGetTransactionHistoryParams creates a new IndexerServiceGetTransactionHistoryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIndexerServiceGetTransactionHistoryParams() *IndexerServiceGetTransactionHistoryParams {
	return &IndexerServiceGetTransactionHistoryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewIndexerServiceGetTransactionHistoryParamsWithTimeout creates a new IndexerServiceGetTransactionHistoryParams object
// with the ability to set a timeout on a request.
func NewIndexerServiceGetTransactionHistoryParamsWithTimeout(timeout time.Duration) *IndexerServiceGetTransactionHistoryParams {
	return &IndexerServiceGetTransactionHistoryParams{
		timeout: timeout,
	}
}

// NewIndexerServiceGetTransactionHistoryParamsWithContext creates a new IndexerServiceGetTransactionHistoryParams object
// with the ability to set a context for a request.
func NewIndexerServiceGetTransactionHistoryParamsWithContext(ctx context.Context) *IndexerServiceGetTransactionHistoryParams {
	return &IndexerServiceGetTransactionHistoryParams{
		Context: ctx,
	}
}

// NewIndexerServiceGetTransactionHistoryParamsWithHTTPClient creates a new IndexerServiceGetTransactionHistoryParams object
// with the ability to set a custom HTTPClient for a request.
func NewIndexerServiceGetTransactionHistoryParamsWithHTTPClient(client *http.Client) *IndexerServiceGetTransactionHistoryParams {
	return &IndexerServiceGetTransactionHistoryParams{
		HTTPClient: client,
	}
}

/*
IndexerServiceGetTransactionHistoryParams contains all the parameters to send to the API endpoint

	for the indexer service get transaction history operation.

	Typically these are written to a http.Request.
*/
type IndexerServiceGetTransactionHistoryParams struct {

	// Address.
	Address string

	// EndTime.
	//
	// Format: int64
	EndTime *string

	// PageIndex.
	//
	// Format: int32
	PageIndex *int32

	// PageSize.
	//
	// Format: int32
	PageSize *int32

	// StartTime.
	//
	// Format: int64
	StartTime *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the indexer service get transaction history params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IndexerServiceGetTransactionHistoryParams) WithDefaults() *IndexerServiceGetTransactionHistoryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the indexer service get transaction history params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IndexerServiceGetTransactionHistoryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the indexer service get transaction history params
func (o *IndexerServiceGetTransactionHistoryParams) WithTimeout(timeout time.Duration) *IndexerServiceGetTransactionHistoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the indexer service get transaction history params
func (o *IndexerServiceGetTransactionHistoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the indexer service get transaction history params
func (o *IndexerServiceGetTransactionHistoryParams) WithContext(ctx context.Context) *IndexerServiceGetTransactionHistoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the indexer service get transaction history params
func (o *IndexerServiceGetTransactionHistoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the indexer service get transaction history params
func (o *IndexerServiceGetTransactionHistoryParams) WithHTTPClient(client *http.Client) *IndexerServiceGetTransactionHistoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the indexer service get transaction history params
func (o *IndexerServiceGetTransactionHistoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddress adds the address to the indexer service get transaction history params
func (o *IndexerServiceGetTransactionHistoryParams) WithAddress(address string) *IndexerServiceGetTransactionHistoryParams {
	o.SetAddress(address)
	return o
}

// SetAddress adds the address to the indexer service get transaction history params
func (o *IndexerServiceGetTransactionHistoryParams) SetAddress(address string) {
	o.Address = address
}

// WithEndTime adds the endTime to the indexer service get transaction history params
func (o *IndexerServiceGetTransactionHistoryParams) WithEndTime(endTime *string) *IndexerServiceGetTransactionHistoryParams {
	o.SetEndTime(endTime)
	return o
}

// SetEndTime adds the endTime to the indexer service get transaction history params
func (o *IndexerServiceGetTransactionHistoryParams) SetEndTime(endTime *string) {
	o.EndTime = endTime
}

// WithPageIndex adds the pageIndex to the indexer service get transaction history params
func (o *IndexerServiceGetTransactionHistoryParams) WithPageIndex(pageIndex *int32) *IndexerServiceGetTransactionHistoryParams {
	o.SetPageIndex(pageIndex)
	return o
}

// SetPageIndex adds the pageIndex to the indexer service get transaction history params
func (o *IndexerServiceGetTransactionHistoryParams) SetPageIndex(pageIndex *int32) {
	o.PageIndex = pageIndex
}

// WithPageSize adds the pageSize to the indexer service get transaction history params
func (o *IndexerServiceGetTransactionHistoryParams) WithPageSize(pageSize *int32) *IndexerServiceGetTransactionHistoryParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the indexer service get transaction history params
func (o *IndexerServiceGetTransactionHistoryParams) SetPageSize(pageSize *int32) {
	o.PageSize = pageSize
}

// WithStartTime adds the startTime to the indexer service get transaction history params
func (o *IndexerServiceGetTransactionHistoryParams) WithStartTime(startTime *string) *IndexerServiceGetTransactionHistoryParams {
	o.SetStartTime(startTime)
	return o
}

// SetStartTime adds the startTime to the indexer service get transaction history params
func (o *IndexerServiceGetTransactionHistoryParams) SetStartTime(startTime *string) {
	o.StartTime = startTime
}

// WriteToRequest writes these params to a swagger request
func (o *IndexerServiceGetTransactionHistoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param address
	if err := r.SetPathParam("address", o.Address); err != nil {
		return err
	}

	if o.EndTime != nil {

		// query param endTime
		var qrEndTime string

		if o.EndTime != nil {
			qrEndTime = *o.EndTime
		}
		qEndTime := qrEndTime
		if qEndTime != "" {

			if err := r.SetQueryParam("endTime", qEndTime); err != nil {
				return err
			}
		}
	}

	if o.PageIndex != nil {

		// query param page.index
		var qrPageIndex int32

		if o.PageIndex != nil {
			qrPageIndex = *o.PageIndex
		}
		qPageIndex := swag.FormatInt32(qrPageIndex)
		if qPageIndex != "" {

			if err := r.SetQueryParam("page.index", qPageIndex); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param page.size
		var qrPageSize int32

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt32(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("page.size", qPageSize); err != nil {
				return err
			}
		}
	}

	if o.StartTime != nil {

		// query param startTime
		var qrStartTime string

		if o.StartTime != nil {
			qrStartTime = *o.StartTime
		}
		qStartTime := qrStartTime
		if qStartTime != "" {

			if err := r.SetQueryParam("startTime", qStartTime); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
