// Code generated by go-swagger; DO NOT EDIT.

package admin_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAdminServiceGetRoundDetailsParams creates a new AdminServiceGetRoundDetailsParams object
// with the default values initialized.
func NewAdminServiceGetRoundDetailsParams() *AdminServiceGetRoundDetailsParams {
	var ()
	return &AdminServiceGetRoundDetailsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAdminServiceGetRoundDetailsParamsWithTimeout creates a new AdminServiceGetRoundDetailsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAdminServiceGetRoundDetailsParamsWithTimeout(timeout time.Duration) *AdminServiceGetRoundDetailsParams {
	var ()
	return &AdminServiceGetRoundDetailsParams{

		timeout: timeout,
	}
}

// NewAdminServiceGetRoundDetailsParamsWithContext creates a new AdminServiceGetRoundDetailsParams object
// with the default values initialized, and the ability to set a context for a request
func NewAdminServiceGetRoundDetailsParamsWithContext(ctx context.Context) *AdminServiceGetRoundDetailsParams {
	var ()
	return &AdminServiceGetRoundDetailsParams{

		Context: ctx,
	}
}

// NewAdminServiceGetRoundDetailsParamsWithHTTPClient creates a new AdminServiceGetRoundDetailsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAdminServiceGetRoundDetailsParamsWithHTTPClient(client *http.Client) *AdminServiceGetRoundDetailsParams {
	var ()
	return &AdminServiceGetRoundDetailsParams{
		HTTPClient: client,
	}
}

/*AdminServiceGetRoundDetailsParams contains all the parameters to send to the API endpoint
for the admin service get round details operation typically these are written to a http.Request
*/
type AdminServiceGetRoundDetailsParams struct {

	/*RoundID*/
	RoundID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the admin service get round details params
func (o *AdminServiceGetRoundDetailsParams) WithTimeout(timeout time.Duration) *AdminServiceGetRoundDetailsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the admin service get round details params
func (o *AdminServiceGetRoundDetailsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the admin service get round details params
func (o *AdminServiceGetRoundDetailsParams) WithContext(ctx context.Context) *AdminServiceGetRoundDetailsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the admin service get round details params
func (o *AdminServiceGetRoundDetailsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the admin service get round details params
func (o *AdminServiceGetRoundDetailsParams) WithHTTPClient(client *http.Client) *AdminServiceGetRoundDetailsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the admin service get round details params
func (o *AdminServiceGetRoundDetailsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRoundID adds the roundID to the admin service get round details params
func (o *AdminServiceGetRoundDetailsParams) WithRoundID(roundID string) *AdminServiceGetRoundDetailsParams {
	o.SetRoundID(roundID)
	return o
}

// SetRoundID adds the roundId to the admin service get round details params
func (o *AdminServiceGetRoundDetailsParams) SetRoundID(roundID string) {
	o.RoundID = roundID
}

// WriteToRequest writes these params to a swagger request
func (o *AdminServiceGetRoundDetailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param roundId
	if err := r.SetPathParam("roundId", o.RoundID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
