// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"database/sql"
)

type Payment struct {
	ID      string
	RoundID string
}

type Receiver struct {
	PaymentID      string
	Pubkey         string
	Amount         int64
	OnchainAddress string
}

type Round struct {
	ID                string
	StartingTimestamp int64
	EndingTimestamp   int64
	Ended             bool
	Failed            bool
	StageCode         int64
	Txid              string
	UnsignedTx        string
	ConnectorAddress  string
	DustAmount        int64
	Version           int64
	Swept             bool
}

type Tx struct {
	ID         int64
	Tx         string
	RoundID    string
	Type       string
	Position   int64
	Txid       sql.NullString
	TreeLevel  sql.NullInt64
	ParentTxid sql.NullString
	IsLeaf     sql.NullBool
}

type Vtxo struct {
	Txid      string
	Vout      int64
	Pubkey    string
	Amount    int64
	PoolTx    string
	SpentBy   string
	Spent     bool
	Redeemed  bool
	Swept     bool
	ExpireAt  int64
	PaymentID sql.NullString
}
