// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V1GetRoundsRequest v1 get rounds request
// swagger:model v1GetRoundsRequest
type V1GetRoundsRequest struct {

	// after
	After string `json:"after,omitempty"`

	// before
	Before string `json:"before,omitempty"`
}

// Validate validates this v1 get rounds request
func (m *V1GetRoundsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1GetRoundsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1GetRoundsRequest) UnmarshalBinary(b []byte) error {
	var res V1GetRoundsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
