// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// V1GetRoundDetailsResponse v1 get round details response
// swagger:model v1GetRoundDetailsResponse
type V1GetRoundDetailsResponse struct {

	// exit addresses
	ExitAddresses []string `json:"exitAddresses"`

	// fees amount
	FeesAmount string `json:"feesAmount,omitempty"`

	// forfeited amount
	ForfeitedAmount string `json:"forfeitedAmount,omitempty"`

	// inputs vtxos
	InputsVtxos []string `json:"inputsVtxos"`

	// outputs vtxos
	OutputsVtxos []string `json:"outputsVtxos"`

	// round Id
	RoundID string `json:"roundId,omitempty"`

	// total exit amount
	TotalExitAmount string `json:"totalExitAmount,omitempty"`

	// total vtxos amount
	TotalVtxosAmount string `json:"totalVtxosAmount,omitempty"`

	// txid
	Txid string `json:"txid,omitempty"`
}

// Validate validates this v1 get round details response
func (m *V1GetRoundDetailsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1GetRoundDetailsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1GetRoundDetailsResponse) UnmarshalBinary(b []byte) error {
	var res V1GetRoundDetailsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
