// Code generated by go-swagger; DO NOT EDIT.

package indexer_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ark-network/ark/pkg/client-sdk/indexer/rest/service/models"
)

// IndexerServiceDeleteSubscriptionReader is a Reader for the IndexerServiceDeleteSubscription structure.
type IndexerServiceDeleteSubscriptionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IndexerServiceDeleteSubscriptionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIndexerServiceDeleteSubscriptionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewIndexerServiceDeleteSubscriptionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIndexerServiceDeleteSubscriptionOK creates a IndexerServiceDeleteSubscriptionOK with default headers values
func NewIndexerServiceDeleteSubscriptionOK() *IndexerServiceDeleteSubscriptionOK {
	return &IndexerServiceDeleteSubscriptionOK{}
}

/*
IndexerServiceDeleteSubscriptionOK describes a response with status code 200, with default header values.

A successful response.
*/
type IndexerServiceDeleteSubscriptionOK struct {
	Payload models.V1DeleteSubscriptionResponse
}

// IsSuccess returns true when this indexer service delete subscription o k response has a 2xx status code
func (o *IndexerServiceDeleteSubscriptionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this indexer service delete subscription o k response has a 3xx status code
func (o *IndexerServiceDeleteSubscriptionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this indexer service delete subscription o k response has a 4xx status code
func (o *IndexerServiceDeleteSubscriptionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this indexer service delete subscription o k response has a 5xx status code
func (o *IndexerServiceDeleteSubscriptionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this indexer service delete subscription o k response a status code equal to that given
func (o *IndexerServiceDeleteSubscriptionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the indexer service delete subscription o k response
func (o *IndexerServiceDeleteSubscriptionOK) Code() int {
	return 200
}

func (o *IndexerServiceDeleteSubscriptionOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/vtxos/subscription/{subscriptionId}][%d] indexerServiceDeleteSubscriptionOK %s", 200, payload)
}

func (o *IndexerServiceDeleteSubscriptionOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/vtxos/subscription/{subscriptionId}][%d] indexerServiceDeleteSubscriptionOK %s", 200, payload)
}

func (o *IndexerServiceDeleteSubscriptionOK) GetPayload() models.V1DeleteSubscriptionResponse {
	return o.Payload
}

func (o *IndexerServiceDeleteSubscriptionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIndexerServiceDeleteSubscriptionDefault creates a IndexerServiceDeleteSubscriptionDefault with default headers values
func NewIndexerServiceDeleteSubscriptionDefault(code int) *IndexerServiceDeleteSubscriptionDefault {
	return &IndexerServiceDeleteSubscriptionDefault{
		_statusCode: code,
	}
}

/*
IndexerServiceDeleteSubscriptionDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type IndexerServiceDeleteSubscriptionDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this indexer service delete subscription default response has a 2xx status code
func (o *IndexerServiceDeleteSubscriptionDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this indexer service delete subscription default response has a 3xx status code
func (o *IndexerServiceDeleteSubscriptionDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this indexer service delete subscription default response has a 4xx status code
func (o *IndexerServiceDeleteSubscriptionDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this indexer service delete subscription default response has a 5xx status code
func (o *IndexerServiceDeleteSubscriptionDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this indexer service delete subscription default response a status code equal to that given
func (o *IndexerServiceDeleteSubscriptionDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the indexer service delete subscription default response
func (o *IndexerServiceDeleteSubscriptionDefault) Code() int {
	return o._statusCode
}

func (o *IndexerServiceDeleteSubscriptionDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/vtxos/subscription/{subscriptionId}][%d] IndexerService_DeleteSubscription default %s", o._statusCode, payload)
}

func (o *IndexerServiceDeleteSubscriptionDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/vtxos/subscription/{subscriptionId}][%d] IndexerService_DeleteSubscription default %s", o._statusCode, payload)
}

func (o *IndexerServiceDeleteSubscriptionDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *IndexerServiceDeleteSubscriptionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
