// Code generated by go-swagger; DO NOT EDIT.

package indexer_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ark-network/ark/pkg/client-sdk/indexer/rest/service/models"
)

// IndexerServiceGetVtxosByOutpointReader is a Reader for the IndexerServiceGetVtxosByOutpoint structure.
type IndexerServiceGetVtxosByOutpointReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IndexerServiceGetVtxosByOutpointReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIndexerServiceGetVtxosByOutpointOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewIndexerServiceGetVtxosByOutpointDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIndexerServiceGetVtxosByOutpointOK creates a IndexerServiceGetVtxosByOutpointOK with default headers values
func NewIndexerServiceGetVtxosByOutpointOK() *IndexerServiceGetVtxosByOutpointOK {
	return &IndexerServiceGetVtxosByOutpointOK{}
}

/*
IndexerServiceGetVtxosByOutpointOK describes a response with status code 200, with default header values.

A successful response.
*/
type IndexerServiceGetVtxosByOutpointOK struct {
	Payload *models.V1GetVtxosByOutpointResponse
}

// IsSuccess returns true when this indexer service get vtxos by outpoint o k response has a 2xx status code
func (o *IndexerServiceGetVtxosByOutpointOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this indexer service get vtxos by outpoint o k response has a 3xx status code
func (o *IndexerServiceGetVtxosByOutpointOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this indexer service get vtxos by outpoint o k response has a 4xx status code
func (o *IndexerServiceGetVtxosByOutpointOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this indexer service get vtxos by outpoint o k response has a 5xx status code
func (o *IndexerServiceGetVtxosByOutpointOK) IsServerError() bool {
	return false
}

// IsCode returns true when this indexer service get vtxos by outpoint o k response a status code equal to that given
func (o *IndexerServiceGetVtxosByOutpointOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the indexer service get vtxos by outpoint o k response
func (o *IndexerServiceGetVtxosByOutpointOK) Code() int {
	return 200
}

func (o *IndexerServiceGetVtxosByOutpointOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/getVtxosByOutpoint/{outpoints}][%d] indexerServiceGetVtxosByOutpointOK %s", 200, payload)
}

func (o *IndexerServiceGetVtxosByOutpointOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/getVtxosByOutpoint/{outpoints}][%d] indexerServiceGetVtxosByOutpointOK %s", 200, payload)
}

func (o *IndexerServiceGetVtxosByOutpointOK) GetPayload() *models.V1GetVtxosByOutpointResponse {
	return o.Payload
}

func (o *IndexerServiceGetVtxosByOutpointOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GetVtxosByOutpointResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIndexerServiceGetVtxosByOutpointDefault creates a IndexerServiceGetVtxosByOutpointDefault with default headers values
func NewIndexerServiceGetVtxosByOutpointDefault(code int) *IndexerServiceGetVtxosByOutpointDefault {
	return &IndexerServiceGetVtxosByOutpointDefault{
		_statusCode: code,
	}
}

/*
IndexerServiceGetVtxosByOutpointDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type IndexerServiceGetVtxosByOutpointDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this indexer service get vtxos by outpoint default response has a 2xx status code
func (o *IndexerServiceGetVtxosByOutpointDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this indexer service get vtxos by outpoint default response has a 3xx status code
func (o *IndexerServiceGetVtxosByOutpointDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this indexer service get vtxos by outpoint default response has a 4xx status code
func (o *IndexerServiceGetVtxosByOutpointDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this indexer service get vtxos by outpoint default response has a 5xx status code
func (o *IndexerServiceGetVtxosByOutpointDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this indexer service get vtxos by outpoint default response a status code equal to that given
func (o *IndexerServiceGetVtxosByOutpointDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the indexer service get vtxos by outpoint default response
func (o *IndexerServiceGetVtxosByOutpointDefault) Code() int {
	return o._statusCode
}

func (o *IndexerServiceGetVtxosByOutpointDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/getVtxosByOutpoint/{outpoints}][%d] IndexerService_GetVtxosByOutpoint default %s", o._statusCode, payload)
}

func (o *IndexerServiceGetVtxosByOutpointDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/getVtxosByOutpoint/{outpoints}][%d] IndexerService_GetVtxosByOutpoint default %s", o._statusCode, payload)
}

func (o *IndexerServiceGetVtxosByOutpointDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *IndexerServiceGetVtxosByOutpointDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
