// Code generated by go-swagger; DO NOT EDIT.

package indexer_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ark-network/ark/pkg/client-sdk/indexer/rest/service/models"
)

// IndexerServiceGetTransactionHistoryReader is a Reader for the IndexerServiceGetTransactionHistory structure.
type IndexerServiceGetTransactionHistoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IndexerServiceGetTransactionHistoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIndexerServiceGetTransactionHistoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewIndexerServiceGetTransactionHistoryDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIndexerServiceGetTransactionHistoryOK creates a IndexerServiceGetTransactionHistoryOK with default headers values
func NewIndexerServiceGetTransactionHistoryOK() *IndexerServiceGetTransactionHistoryOK {
	return &IndexerServiceGetTransactionHistoryOK{}
}

/*
IndexerServiceGetTransactionHistoryOK describes a response with status code 200, with default header values.

A successful response.
*/
type IndexerServiceGetTransactionHistoryOK struct {
	Payload *models.V1GetTransactionHistoryResponse
}

// IsSuccess returns true when this indexer service get transaction history o k response has a 2xx status code
func (o *IndexerServiceGetTransactionHistoryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this indexer service get transaction history o k response has a 3xx status code
func (o *IndexerServiceGetTransactionHistoryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this indexer service get transaction history o k response has a 4xx status code
func (o *IndexerServiceGetTransactionHistoryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this indexer service get transaction history o k response has a 5xx status code
func (o *IndexerServiceGetTransactionHistoryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this indexer service get transaction history o k response a status code equal to that given
func (o *IndexerServiceGetTransactionHistoryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the indexer service get transaction history o k response
func (o *IndexerServiceGetTransactionHistoryOK) Code() int {
	return 200
}

func (o *IndexerServiceGetTransactionHistoryOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/history/{address}][%d] indexerServiceGetTransactionHistoryOK %s", 200, payload)
}

func (o *IndexerServiceGetTransactionHistoryOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/history/{address}][%d] indexerServiceGetTransactionHistoryOK %s", 200, payload)
}

func (o *IndexerServiceGetTransactionHistoryOK) GetPayload() *models.V1GetTransactionHistoryResponse {
	return o.Payload
}

func (o *IndexerServiceGetTransactionHistoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GetTransactionHistoryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIndexerServiceGetTransactionHistoryDefault creates a IndexerServiceGetTransactionHistoryDefault with default headers values
func NewIndexerServiceGetTransactionHistoryDefault(code int) *IndexerServiceGetTransactionHistoryDefault {
	return &IndexerServiceGetTransactionHistoryDefault{
		_statusCode: code,
	}
}

/*
IndexerServiceGetTransactionHistoryDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type IndexerServiceGetTransactionHistoryDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this indexer service get transaction history default response has a 2xx status code
func (o *IndexerServiceGetTransactionHistoryDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this indexer service get transaction history default response has a 3xx status code
func (o *IndexerServiceGetTransactionHistoryDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this indexer service get transaction history default response has a 4xx status code
func (o *IndexerServiceGetTransactionHistoryDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this indexer service get transaction history default response has a 5xx status code
func (o *IndexerServiceGetTransactionHistoryDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this indexer service get transaction history default response a status code equal to that given
func (o *IndexerServiceGetTransactionHistoryDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the indexer service get transaction history default response
func (o *IndexerServiceGetTransactionHistoryDefault) Code() int {
	return o._statusCode
}

func (o *IndexerServiceGetTransactionHistoryDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/history/{address}][%d] IndexerService_GetTransactionHistory default %s", o._statusCode, payload)
}

func (o *IndexerServiceGetTransactionHistoryDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/history/{address}][%d] IndexerService_GetTransactionHistory default %s", o._statusCode, payload)
}

func (o *IndexerServiceGetTransactionHistoryDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *IndexerServiceGetTransactionHistoryDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
