// Code generated by go-swagger; DO NOT EDIT.

package indexer_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ark-network/ark/pkg/client-sdk/indexer/rest/service/models"
)

// NewIndexerServiceSubscribeForScriptsParams creates a new IndexerServiceSubscribeForScriptsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIndexerServiceSubscribeForScriptsParams() *IndexerServiceSubscribeForScriptsParams {
	return &IndexerServiceSubscribeForScriptsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewIndexerServiceSubscribeForScriptsParamsWithTimeout creates a new IndexerServiceSubscribeForScriptsParams object
// with the ability to set a timeout on a request.
func NewIndexerServiceSubscribeForScriptsParamsWithTimeout(timeout time.Duration) *IndexerServiceSubscribeForScriptsParams {
	return &IndexerServiceSubscribeForScriptsParams{
		timeout: timeout,
	}
}

// NewIndexerServiceSubscribeForScriptsParamsWithContext creates a new IndexerServiceSubscribeForScriptsParams object
// with the ability to set a context for a request.
func NewIndexerServiceSubscribeForScriptsParamsWithContext(ctx context.Context) *IndexerServiceSubscribeForScriptsParams {
	return &IndexerServiceSubscribeForScriptsParams{
		Context: ctx,
	}
}

// NewIndexerServiceSubscribeForScriptsParamsWithHTTPClient creates a new IndexerServiceSubscribeForScriptsParams object
// with the ability to set a custom HTTPClient for a request.
func NewIndexerServiceSubscribeForScriptsParamsWithHTTPClient(client *http.Client) *IndexerServiceSubscribeForScriptsParams {
	return &IndexerServiceSubscribeForScriptsParams{
		HTTPClient: client,
	}
}

/*
IndexerServiceSubscribeForScriptsParams contains all the parameters to send to the API endpoint

	for the indexer service subscribe for scripts operation.

	Typically these are written to a http.Request.
*/
type IndexerServiceSubscribeForScriptsParams struct {

	// Body.
	Body *models.V1SubscribeForScriptsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the indexer service subscribe for scripts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IndexerServiceSubscribeForScriptsParams) WithDefaults() *IndexerServiceSubscribeForScriptsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the indexer service subscribe for scripts params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IndexerServiceSubscribeForScriptsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the indexer service subscribe for scripts params
func (o *IndexerServiceSubscribeForScriptsParams) WithTimeout(timeout time.Duration) *IndexerServiceSubscribeForScriptsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the indexer service subscribe for scripts params
func (o *IndexerServiceSubscribeForScriptsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the indexer service subscribe for scripts params
func (o *IndexerServiceSubscribeForScriptsParams) WithContext(ctx context.Context) *IndexerServiceSubscribeForScriptsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the indexer service subscribe for scripts params
func (o *IndexerServiceSubscribeForScriptsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the indexer service subscribe for scripts params
func (o *IndexerServiceSubscribeForScriptsParams) WithHTTPClient(client *http.Client) *IndexerServiceSubscribeForScriptsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the indexer service subscribe for scripts params
func (o *IndexerServiceSubscribeForScriptsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the indexer service subscribe for scripts params
func (o *IndexerServiceSubscribeForScriptsParams) WithBody(body *models.V1SubscribeForScriptsRequest) *IndexerServiceSubscribeForScriptsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the indexer service subscribe for scripts params
func (o *IndexerServiceSubscribeForScriptsParams) SetBody(body *models.V1SubscribeForScriptsRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *IndexerServiceSubscribeForScriptsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
