// Code generated by go-swagger; DO NOT EDIT.

package indexer_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewIndexerServiceGetSweptCommitmentTxParams creates a new IndexerServiceGetSweptCommitmentTxParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIndexerServiceGetSweptCommitmentTxParams() *IndexerServiceGetSweptCommitmentTxParams {
	return &IndexerServiceGetSweptCommitmentTxParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewIndexerServiceGetSweptCommitmentTxParamsWithTimeout creates a new IndexerServiceGetSweptCommitmentTxParams object
// with the ability to set a timeout on a request.
func NewIndexerServiceGetSweptCommitmentTxParamsWithTimeout(timeout time.Duration) *IndexerServiceGetSweptCommitmentTxParams {
	return &IndexerServiceGetSweptCommitmentTxParams{
		timeout: timeout,
	}
}

// NewIndexerServiceGetSweptCommitmentTxParamsWithContext creates a new IndexerServiceGetSweptCommitmentTxParams object
// with the ability to set a context for a request.
func NewIndexerServiceGetSweptCommitmentTxParamsWithContext(ctx context.Context) *IndexerServiceGetSweptCommitmentTxParams {
	return &IndexerServiceGetSweptCommitmentTxParams{
		Context: ctx,
	}
}

// NewIndexerServiceGetSweptCommitmentTxParamsWithHTTPClient creates a new IndexerServiceGetSweptCommitmentTxParams object
// with the ability to set a custom HTTPClient for a request.
func NewIndexerServiceGetSweptCommitmentTxParamsWithHTTPClient(client *http.Client) *IndexerServiceGetSweptCommitmentTxParams {
	return &IndexerServiceGetSweptCommitmentTxParams{
		HTTPClient: client,
	}
}

/*
IndexerServiceGetSweptCommitmentTxParams contains all the parameters to send to the API endpoint

	for the indexer service get swept commitment tx operation.

	Typically these are written to a http.Request.
*/
type IndexerServiceGetSweptCommitmentTxParams struct {

	// Txid.
	Txid string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the indexer service get swept commitment tx params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IndexerServiceGetSweptCommitmentTxParams) WithDefaults() *IndexerServiceGetSweptCommitmentTxParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the indexer service get swept commitment tx params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IndexerServiceGetSweptCommitmentTxParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the indexer service get swept commitment tx params
func (o *IndexerServiceGetSweptCommitmentTxParams) WithTimeout(timeout time.Duration) *IndexerServiceGetSweptCommitmentTxParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the indexer service get swept commitment tx params
func (o *IndexerServiceGetSweptCommitmentTxParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the indexer service get swept commitment tx params
func (o *IndexerServiceGetSweptCommitmentTxParams) WithContext(ctx context.Context) *IndexerServiceGetSweptCommitmentTxParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the indexer service get swept commitment tx params
func (o *IndexerServiceGetSweptCommitmentTxParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the indexer service get swept commitment tx params
func (o *IndexerServiceGetSweptCommitmentTxParams) WithHTTPClient(client *http.Client) *IndexerServiceGetSweptCommitmentTxParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the indexer service get swept commitment tx params
func (o *IndexerServiceGetSweptCommitmentTxParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTxid adds the txid to the indexer service get swept commitment tx params
func (o *IndexerServiceGetSweptCommitmentTxParams) WithTxid(txid string) *IndexerServiceGetSweptCommitmentTxParams {
	o.SetTxid(txid)
	return o
}

// SetTxid adds the txid to the indexer service get swept commitment tx params
func (o *IndexerServiceGetSweptCommitmentTxParams) SetTxid(txid string) {
	o.Txid = txid
}

// WriteToRequest writes these params to a swagger request
func (o *IndexerServiceGetSweptCommitmentTxParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param txid
	if err := r.SetPathParam("txid", o.Txid); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
