// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"database/sql"
)

type Tx struct {
	Txid      string
	TxidType  string
	Amount    int64
	Type      string
	Settled   bool
	CreatedAt int64
	Hex       sql.NullString
}

type Vtxo struct {
	Txid           string
	Vout           int64
	Script         string
	Amount         int64
	CommitmentTxid string
	SpentBy        sql.NullString
	Spent          bool
	ExpiresAt      int64
	CreatedAt      int64
	Preconfirmed   bool
	Swept          bool
	Redeemed       bool
}
