// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1DeleteSubscriptionResponse v1 delete subscription response
//
// swagger:model v1DeleteSubscriptionResponse
type V1DeleteSubscriptionResponse interface{}
