// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1GetCommitmentTxLeavesResponse v1 get commitment tx leaves response
//
// swagger:model v1GetCommitmentTxLeavesResponse
type V1GetCommitmentTxLeavesResponse struct {

	// leaves
	Leaves []*V1IndexerOutpoint `json:"leaves"`

	// page
	Page *V1IndexerPageResponse `json:"page,omitempty"`
}

// Validate validates this v1 get commitment tx leaves response
func (m *V1GetCommitmentTxLeavesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLeaves(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1GetCommitmentTxLeavesResponse) validateLeaves(formats strfmt.Registry) error {
	if swag.IsZero(m.Leaves) { // not required
		return nil
	}

	for i := 0; i < len(m.Leaves); i++ {
		if swag.IsZero(m.Leaves[i]) { // not required
			continue
		}

		if m.Leaves[i] != nil {
			if err := m.Leaves[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("leaves" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("leaves" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1GetCommitmentTxLeavesResponse) validatePage(formats strfmt.Registry) error {
	if swag.IsZero(m.Page) { // not required
		return nil
	}

	if m.Page != nil {
		if err := m.Page.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("page")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("page")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 get commitment tx leaves response based on the context it is used
func (m *V1GetCommitmentTxLeavesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLeaves(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1GetCommitmentTxLeavesResponse) contextValidateLeaves(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Leaves); i++ {

		if m.Leaves[i] != nil {

			if swag.IsZero(m.Leaves[i]) { // not required
				return nil
			}

			if err := m.Leaves[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("leaves" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("leaves" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1GetCommitmentTxLeavesResponse) contextValidatePage(ctx context.Context, formats strfmt.Registry) error {

	if m.Page != nil {

		if swag.IsZero(m.Page) { // not required
			return nil
		}

		if err := m.Page.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("page")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("page")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1GetCommitmentTxLeavesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1GetCommitmentTxLeavesResponse) UnmarshalBinary(b []byte) error {
	var res V1GetCommitmentTxLeavesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
