// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1IndexerNode v1 indexer node
//
// swagger:model v1IndexerNode
type V1IndexerNode struct {

	// vout -> txid
	Children map[string]string `json:"children,omitempty"`

	// txid
	Txid string `json:"txid,omitempty"`
}

// Validate validates this v1 indexer node
func (m *V1IndexerNode) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 indexer node based on context it is used
func (m *V1IndexerNode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1IndexerNode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1IndexerNode) UnmarshalBinary(b []byte) error {
	var res V1IndexerNode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
