// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1IndexerChain v1 indexer chain
//
// swagger:model v1IndexerChain
type V1IndexerChain struct {

	// expires at
	ExpiresAt string `json:"expiresAt,omitempty"`

	// spends
	Spends []*V1IndexerChainedTx `json:"spends"`

	// txid
	Txid string `json:"txid,omitempty"`
}

// Validate validates this v1 indexer chain
func (m *V1IndexerChain) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSpends(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1IndexerChain) validateSpends(formats strfmt.Registry) error {
	if swag.IsZero(m.Spends) { // not required
		return nil
	}

	for i := 0; i < len(m.Spends); i++ {
		if swag.IsZero(m.Spends[i]) { // not required
			continue
		}

		if m.Spends[i] != nil {
			if err := m.Spends[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("spends" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("spends" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v1 indexer chain based on the context it is used
func (m *V1IndexerChain) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSpends(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1IndexerChain) contextValidateSpends(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Spends); i++ {

		if m.Spends[i] != nil {

			if swag.IsZero(m.Spends[i]) { // not required
				return nil
			}

			if err := m.Spends[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("spends" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("spends" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1IndexerChain) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1IndexerChain) UnmarshalBinary(b []byte) error {
	var res V1IndexerChain
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
