// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// V1UnsubscribeForScriptsResponse v1 unsubscribe for scripts response
//
// swagger:model v1UnsubscribeForScriptsResponse
type V1UnsubscribeForScriptsResponse interface{}
