// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1UnsubscribeForAddressesRequest v1 unsubscribe for addresses request
//
// swagger:model v1UnsubscribeForAddressesRequest
type V1UnsubscribeForAddressesRequest struct {

	// if empty, unsubscribe all addresses
	Addresses []string `json:"addresses"`

	// subscription Id
	SubscriptionID string `json:"subscriptionId,omitempty"`
}

// Validate validates this v1 unsubscribe for addresses request
func (m *V1UnsubscribeForAddressesRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 unsubscribe for addresses request based on context it is used
func (m *V1UnsubscribeForAddressesRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1UnsubscribeForAddressesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1UnsubscribeForAddressesRequest) UnmarshalBinary(b []byte) error {
	var res V1UnsubscribeForAddressesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
