// Code generated by go-swagger; DO NOT EDIT.

package ark_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ark-network/ark/pkg/client-sdk/client/rest/service/models"
)

// ArkServiceSubmitTxReader is a Reader for the ArkServiceSubmitTx structure.
type ArkServiceSubmitTxReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ArkServiceSubmitTxReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewArkServiceSubmitTxOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewArkServiceSubmitTxDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewArkServiceSubmitTxOK creates a ArkServiceSubmitTxOK with default headers values
func NewArkServiceSubmitTxOK() *ArkServiceSubmitTxOK {
	return &ArkServiceSubmitTxOK{}
}

/*
ArkServiceSubmitTxOK describes a response with status code 200, with default header values.

A successful response.
*/
type ArkServiceSubmitTxOK struct {
	Payload *models.V1SubmitTxResponse
}

// IsSuccess returns true when this ark service submit tx o k response has a 2xx status code
func (o *ArkServiceSubmitTxOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ark service submit tx o k response has a 3xx status code
func (o *ArkServiceSubmitTxOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ark service submit tx o k response has a 4xx status code
func (o *ArkServiceSubmitTxOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ark service submit tx o k response has a 5xx status code
func (o *ArkServiceSubmitTxOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ark service submit tx o k response a status code equal to that given
func (o *ArkServiceSubmitTxOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the ark service submit tx o k response
func (o *ArkServiceSubmitTxOK) Code() int {
	return 200
}

func (o *ArkServiceSubmitTxOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/tx/submit][%d] arkServiceSubmitTxOK %s", 200, payload)
}

func (o *ArkServiceSubmitTxOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/tx/submit][%d] arkServiceSubmitTxOK %s", 200, payload)
}

func (o *ArkServiceSubmitTxOK) GetPayload() *models.V1SubmitTxResponse {
	return o.Payload
}

func (o *ArkServiceSubmitTxOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1SubmitTxResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewArkServiceSubmitTxDefault creates a ArkServiceSubmitTxDefault with default headers values
func NewArkServiceSubmitTxDefault(code int) *ArkServiceSubmitTxDefault {
	return &ArkServiceSubmitTxDefault{
		_statusCode: code,
	}
}

/*
ArkServiceSubmitTxDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ArkServiceSubmitTxDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this ark service submit tx default response has a 2xx status code
func (o *ArkServiceSubmitTxDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ark service submit tx default response has a 3xx status code
func (o *ArkServiceSubmitTxDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ark service submit tx default response has a 4xx status code
func (o *ArkServiceSubmitTxDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ark service submit tx default response has a 5xx status code
func (o *ArkServiceSubmitTxDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ark service submit tx default response a status code equal to that given
func (o *ArkServiceSubmitTxDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the ark service submit tx default response
func (o *ArkServiceSubmitTxDefault) Code() int {
	return o._statusCode
}

func (o *ArkServiceSubmitTxDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/tx/submit][%d] ArkService_SubmitTx default %s", o._statusCode, payload)
}

func (o *ArkServiceSubmitTxDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/tx/submit][%d] ArkService_SubmitTx default %s", o._statusCode, payload)
}

func (o *ArkServiceSubmitTxDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ArkServiceSubmitTxDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
