// Code generated by go-swagger; DO NOT EDIT.

package ark_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ark-network/ark/pkg/client-sdk/client/rest/service/models"
)

// NewArkServiceCompletePaymentParams creates a new ArkServiceCompletePaymentParams object
// with the default values initialized.
func NewArkServiceCompletePaymentParams() *ArkServiceCompletePaymentParams {
	var ()
	return &ArkServiceCompletePaymentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewArkServiceCompletePaymentParamsWithTimeout creates a new ArkServiceCompletePaymentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewArkServiceCompletePaymentParamsWithTimeout(timeout time.Duration) *ArkServiceCompletePaymentParams {
	var ()
	return &ArkServiceCompletePaymentParams{

		timeout: timeout,
	}
}

// NewArkServiceCompletePaymentParamsWithContext creates a new ArkServiceCompletePaymentParams object
// with the default values initialized, and the ability to set a context for a request
func NewArkServiceCompletePaymentParamsWithContext(ctx context.Context) *ArkServiceCompletePaymentParams {
	var ()
	return &ArkServiceCompletePaymentParams{

		Context: ctx,
	}
}

// NewArkServiceCompletePaymentParamsWithHTTPClient creates a new ArkServiceCompletePaymentParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewArkServiceCompletePaymentParamsWithHTTPClient(client *http.Client) *ArkServiceCompletePaymentParams {
	var ()
	return &ArkServiceCompletePaymentParams{
		HTTPClient: client,
	}
}

/*ArkServiceCompletePaymentParams contains all the parameters to send to the API endpoint
for the ark service complete payment operation typically these are written to a http.Request
*/
type ArkServiceCompletePaymentParams struct {

	/*Body*/
	Body *models.V1CompletePaymentRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the ark service complete payment params
func (o *ArkServiceCompletePaymentParams) WithTimeout(timeout time.Duration) *ArkServiceCompletePaymentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ark service complete payment params
func (o *ArkServiceCompletePaymentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ark service complete payment params
func (o *ArkServiceCompletePaymentParams) WithContext(ctx context.Context) *ArkServiceCompletePaymentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ark service complete payment params
func (o *ArkServiceCompletePaymentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ark service complete payment params
func (o *ArkServiceCompletePaymentParams) WithHTTPClient(client *http.Client) *ArkServiceCompletePaymentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ark service complete payment params
func (o *ArkServiceCompletePaymentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the ark service complete payment params
func (o *ArkServiceCompletePaymentParams) WithBody(body *models.V1CompletePaymentRequest) *ArkServiceCompletePaymentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the ark service complete payment params
func (o *ArkServiceCompletePaymentParams) SetBody(body *models.V1CompletePaymentRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ArkServiceCompletePaymentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
