// Code generated by go-swagger; DO NOT EDIT.

package ark_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ark-network/ark/pkg/client-sdk/client/rest/service/models"
)

// ArkServiceSendTreeSignaturesReader is a Reader for the ArkServiceSendTreeSignatures structure.
type ArkServiceSendTreeSignaturesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ArkServiceSendTreeSignaturesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewArkServiceSendTreeSignaturesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewArkServiceSendTreeSignaturesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewArkServiceSendTreeSignaturesOK creates a ArkServiceSendTreeSignaturesOK with default headers values
func NewArkServiceSendTreeSignaturesOK() *ArkServiceSendTreeSignaturesOK {
	return &ArkServiceSendTreeSignaturesOK{}
}

/*
ArkServiceSendTreeSignaturesOK describes a response with status code 200, with default header values.

A successful response.
*/
type ArkServiceSendTreeSignaturesOK struct {
	Payload models.V1SendTreeSignaturesResponse
}

// IsSuccess returns true when this ark service send tree signatures o k response has a 2xx status code
func (o *ArkServiceSendTreeSignaturesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ark service send tree signatures o k response has a 3xx status code
func (o *ArkServiceSendTreeSignaturesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ark service send tree signatures o k response has a 4xx status code
func (o *ArkServiceSendTreeSignaturesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ark service send tree signatures o k response has a 5xx status code
func (o *ArkServiceSendTreeSignaturesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ark service send tree signatures o k response a status code equal to that given
func (o *ArkServiceSendTreeSignaturesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the ark service send tree signatures o k response
func (o *ArkServiceSendTreeSignaturesOK) Code() int {
	return 200
}

func (o *ArkServiceSendTreeSignaturesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/payment/tree/signatures][%d] arkServiceSendTreeSignaturesOK %s", 200, payload)
}

func (o *ArkServiceSendTreeSignaturesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/payment/tree/signatures][%d] arkServiceSendTreeSignaturesOK %s", 200, payload)
}

func (o *ArkServiceSendTreeSignaturesOK) GetPayload() models.V1SendTreeSignaturesResponse {
	return o.Payload
}

func (o *ArkServiceSendTreeSignaturesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewArkServiceSendTreeSignaturesDefault creates a ArkServiceSendTreeSignaturesDefault with default headers values
func NewArkServiceSendTreeSignaturesDefault(code int) *ArkServiceSendTreeSignaturesDefault {
	return &ArkServiceSendTreeSignaturesDefault{
		_statusCode: code,
	}
}

/*
ArkServiceSendTreeSignaturesDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ArkServiceSendTreeSignaturesDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this ark service send tree signatures default response has a 2xx status code
func (o *ArkServiceSendTreeSignaturesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ark service send tree signatures default response has a 3xx status code
func (o *ArkServiceSendTreeSignaturesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ark service send tree signatures default response has a 4xx status code
func (o *ArkServiceSendTreeSignaturesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ark service send tree signatures default response has a 5xx status code
func (o *ArkServiceSendTreeSignaturesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ark service send tree signatures default response a status code equal to that given
func (o *ArkServiceSendTreeSignaturesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the ark service send tree signatures default response
func (o *ArkServiceSendTreeSignaturesDefault) Code() int {
	return o._statusCode
}

func (o *ArkServiceSendTreeSignaturesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/payment/tree/signatures][%d] ArkService_SendTreeSignatures default %s", o._statusCode, payload)
}

func (o *ArkServiceSendTreeSignaturesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/payment/tree/signatures][%d] ArkService_SendTreeSignatures default %s", o._statusCode, payload)
}

func (o *ArkServiceSendTreeSignaturesDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ArkServiceSendTreeSignaturesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
