// Code generated by go-swagger; DO NOT EDIT.

package ark_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ark-network/ark/pkg/client-sdk/client/rest/service/models"
)

// ArkServiceFinalizeTxReader is a Reader for the ArkServiceFinalizeTx structure.
type ArkServiceFinalizeTxReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ArkServiceFinalizeTxReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewArkServiceFinalizeTxOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewArkServiceFinalizeTxDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewArkServiceFinalizeTxOK creates a ArkServiceFinalizeTxOK with default headers values
func NewArkServiceFinalizeTxOK() *ArkServiceFinalizeTxOK {
	return &ArkServiceFinalizeTxOK{}
}

/*
ArkServiceFinalizeTxOK describes a response with status code 200, with default header values.

A successful response.
*/
type ArkServiceFinalizeTxOK struct {
	Payload models.V1FinalizeTxResponse
}

// IsSuccess returns true when this ark service finalize tx o k response has a 2xx status code
func (o *ArkServiceFinalizeTxOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ark service finalize tx o k response has a 3xx status code
func (o *ArkServiceFinalizeTxOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ark service finalize tx o k response has a 4xx status code
func (o *ArkServiceFinalizeTxOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ark service finalize tx o k response has a 5xx status code
func (o *ArkServiceFinalizeTxOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ark service finalize tx o k response a status code equal to that given
func (o *ArkServiceFinalizeTxOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the ark service finalize tx o k response
func (o *ArkServiceFinalizeTxOK) Code() int {
	return 200
}

func (o *ArkServiceFinalizeTxOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/tx/finalize][%d] arkServiceFinalizeTxOK %s", 200, payload)
}

func (o *ArkServiceFinalizeTxOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/tx/finalize][%d] arkServiceFinalizeTxOK %s", 200, payload)
}

func (o *ArkServiceFinalizeTxOK) GetPayload() models.V1FinalizeTxResponse {
	return o.Payload
}

func (o *ArkServiceFinalizeTxOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewArkServiceFinalizeTxDefault creates a ArkServiceFinalizeTxDefault with default headers values
func NewArkServiceFinalizeTxDefault(code int) *ArkServiceFinalizeTxDefault {
	return &ArkServiceFinalizeTxDefault{
		_statusCode: code,
	}
}

/*
ArkServiceFinalizeTxDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ArkServiceFinalizeTxDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this ark service finalize tx default response has a 2xx status code
func (o *ArkServiceFinalizeTxDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ark service finalize tx default response has a 3xx status code
func (o *ArkServiceFinalizeTxDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ark service finalize tx default response has a 4xx status code
func (o *ArkServiceFinalizeTxDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ark service finalize tx default response has a 5xx status code
func (o *ArkServiceFinalizeTxDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ark service finalize tx default response a status code equal to that given
func (o *ArkServiceFinalizeTxDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the ark service finalize tx default response
func (o *ArkServiceFinalizeTxDefault) Code() int {
	return o._statusCode
}

func (o *ArkServiceFinalizeTxDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/tx/finalize][%d] ArkService_FinalizeTx default %s", o._statusCode, payload)
}

func (o *ArkServiceFinalizeTxDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/tx/finalize][%d] ArkService_FinalizeTx default %s", o._statusCode, payload)
}

func (o *ArkServiceFinalizeTxDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ArkServiceFinalizeTxDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
