// Code generated by go-swagger; DO NOT EDIT.

package ark_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ark-network/ark/pkg/client-sdk/client/rest/service/models"
)

// NewArkServiceSendTreeSignaturesParams creates a new ArkServiceSendTreeSignaturesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewArkServiceSendTreeSignaturesParams() *ArkServiceSendTreeSignaturesParams {
	return &ArkServiceSendTreeSignaturesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewArkServiceSendTreeSignaturesParamsWithTimeout creates a new ArkServiceSendTreeSignaturesParams object
// with the ability to set a timeout on a request.
func NewArkServiceSendTreeSignaturesParamsWithTimeout(timeout time.Duration) *ArkServiceSendTreeSignaturesParams {
	return &ArkServiceSendTreeSignaturesParams{
		timeout: timeout,
	}
}

// NewArkServiceSendTreeSignaturesParamsWithContext creates a new ArkServiceSendTreeSignaturesParams object
// with the ability to set a context for a request.
func NewArkServiceSendTreeSignaturesParamsWithContext(ctx context.Context) *ArkServiceSendTreeSignaturesParams {
	return &ArkServiceSendTreeSignaturesParams{
		Context: ctx,
	}
}

// NewArkServiceSendTreeSignaturesParamsWithHTTPClient creates a new ArkServiceSendTreeSignaturesParams object
// with the ability to set a custom HTTPClient for a request.
func NewArkServiceSendTreeSignaturesParamsWithHTTPClient(client *http.Client) *ArkServiceSendTreeSignaturesParams {
	return &ArkServiceSendTreeSignaturesParams{
		HTTPClient: client,
	}
}

/*
ArkServiceSendTreeSignaturesParams contains all the parameters to send to the API endpoint

	for the ark service send tree signatures operation.

	Typically these are written to a http.Request.
*/
type ArkServiceSendTreeSignaturesParams struct {

	// Body.
	Body *models.V1SendTreeSignaturesRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the ark service send tree signatures params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ArkServiceSendTreeSignaturesParams) WithDefaults() *ArkServiceSendTreeSignaturesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the ark service send tree signatures params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ArkServiceSendTreeSignaturesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the ark service send tree signatures params
func (o *ArkServiceSendTreeSignaturesParams) WithTimeout(timeout time.Duration) *ArkServiceSendTreeSignaturesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ark service send tree signatures params
func (o *ArkServiceSendTreeSignaturesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ark service send tree signatures params
func (o *ArkServiceSendTreeSignaturesParams) WithContext(ctx context.Context) *ArkServiceSendTreeSignaturesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ark service send tree signatures params
func (o *ArkServiceSendTreeSignaturesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ark service send tree signatures params
func (o *ArkServiceSendTreeSignaturesParams) WithHTTPClient(client *http.Client) *ArkServiceSendTreeSignaturesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ark service send tree signatures params
func (o *ArkServiceSendTreeSignaturesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the ark service send tree signatures params
func (o *ArkServiceSendTreeSignaturesParams) WithBody(body *models.V1SendTreeSignaturesRequest) *ArkServiceSendTreeSignaturesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the ark service send tree signatures params
func (o *ArkServiceSendTreeSignaturesParams) SetBody(body *models.V1SendTreeSignaturesRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ArkServiceSendTreeSignaturesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
