// Code generated by go-swagger; DO NOT EDIT.

package ark_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/ark-network/ark/pkg/client-sdk/client/rest/service/models"
)

// ArkServiceCreatePaymentReader is a Reader for the ArkServiceCreatePayment structure.
type ArkServiceCreatePaymentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ArkServiceCreatePaymentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewArkServiceCreatePaymentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewArkServiceCreatePaymentDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewArkServiceCreatePaymentOK creates a ArkServiceCreatePaymentOK with default headers values
func NewArkServiceCreatePaymentOK() *ArkServiceCreatePaymentOK {
	return &ArkServiceCreatePaymentOK{}
}

/*ArkServiceCreatePaymentOK handles this case with default header values.

A successful response.
*/
type ArkServiceCreatePaymentOK struct {
	Payload *models.V1CreatePaymentResponse
}

func (o *ArkServiceCreatePaymentOK) Error() string {
	return fmt.Sprintf("[POST /v1/payment][%d] arkServiceCreatePaymentOK  %+v", 200, o.Payload)
}

func (o *ArkServiceCreatePaymentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1CreatePaymentResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewArkServiceCreatePaymentDefault creates a ArkServiceCreatePaymentDefault with default headers values
func NewArkServiceCreatePaymentDefault(code int) *ArkServiceCreatePaymentDefault {
	return &ArkServiceCreatePaymentDefault{
		_statusCode: code,
	}
}

/*ArkServiceCreatePaymentDefault handles this case with default header values.

An unexpected error response.
*/
type ArkServiceCreatePaymentDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the ark service create payment default response
func (o *ArkServiceCreatePaymentDefault) Code() int {
	return o._statusCode
}

func (o *ArkServiceCreatePaymentDefault) Error() string {
	return fmt.Sprintf("[POST /v1/payment][%d] ArkService_CreatePayment default  %+v", o._statusCode, o.Payload)
}

func (o *ArkServiceCreatePaymentDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
