// Code generated by go-swagger; DO NOT EDIT.

package ark_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ark-network/ark/pkg/client-sdk/client/rest/service/models"
)

// NewArkServiceRegisterIntentParams creates a new ArkServiceRegisterIntentParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewArkServiceRegisterIntentParams() *ArkServiceRegisterIntentParams {
	return &ArkServiceRegisterIntentParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewArkServiceRegisterIntentParamsWithTimeout creates a new ArkServiceRegisterIntentParams object
// with the ability to set a timeout on a request.
func NewArkServiceRegisterIntentParamsWithTimeout(timeout time.Duration) *ArkServiceRegisterIntentParams {
	return &ArkServiceRegisterIntentParams{
		timeout: timeout,
	}
}

// NewArkServiceRegisterIntentParamsWithContext creates a new ArkServiceRegisterIntentParams object
// with the ability to set a context for a request.
func NewArkServiceRegisterIntentParamsWithContext(ctx context.Context) *ArkServiceRegisterIntentParams {
	return &ArkServiceRegisterIntentParams{
		Context: ctx,
	}
}

// NewArkServiceRegisterIntentParamsWithHTTPClient creates a new ArkServiceRegisterIntentParams object
// with the ability to set a custom HTTPClient for a request.
func NewArkServiceRegisterIntentParamsWithHTTPClient(client *http.Client) *ArkServiceRegisterIntentParams {
	return &ArkServiceRegisterIntentParams{
		HTTPClient: client,
	}
}

/*
ArkServiceRegisterIntentParams contains all the parameters to send to the API endpoint

	for the ark service register intent operation.

	Typically these are written to a http.Request.
*/
type ArkServiceRegisterIntentParams struct {

	// Body.
	Body *models.V1RegisterIntentRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the ark service register intent params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ArkServiceRegisterIntentParams) WithDefaults() *ArkServiceRegisterIntentParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the ark service register intent params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ArkServiceRegisterIntentParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the ark service register intent params
func (o *ArkServiceRegisterIntentParams) WithTimeout(timeout time.Duration) *ArkServiceRegisterIntentParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ark service register intent params
func (o *ArkServiceRegisterIntentParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ark service register intent params
func (o *ArkServiceRegisterIntentParams) WithContext(ctx context.Context) *ArkServiceRegisterIntentParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ark service register intent params
func (o *ArkServiceRegisterIntentParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ark service register intent params
func (o *ArkServiceRegisterIntentParams) WithHTTPClient(client *http.Client) *ArkServiceRegisterIntentParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ark service register intent params
func (o *ArkServiceRegisterIntentParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the ark service register intent params
func (o *ArkServiceRegisterIntentParams) WithBody(body *models.V1RegisterIntentRequest) *ArkServiceRegisterIntentParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the ark service register intent params
func (o *ArkServiceRegisterIntentParams) SetBody(body *models.V1RegisterIntentRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ArkServiceRegisterIntentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
