// Code generated by go-swagger; DO NOT EDIT.

package ark_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ark-network/ark/pkg/client-sdk/client/rest/service/models"
)

// ArkServiceReverseBoardingAddressReader is a Reader for the ArkServiceReverseBoardingAddress structure.
type ArkServiceReverseBoardingAddressReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ArkServiceReverseBoardingAddressReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewArkServiceReverseBoardingAddressOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewArkServiceReverseBoardingAddressDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewArkServiceReverseBoardingAddressOK creates a ArkServiceReverseBoardingAddressOK with default headers values
func NewArkServiceReverseBoardingAddressOK() *ArkServiceReverseBoardingAddressOK {
	return &ArkServiceReverseBoardingAddressOK{}
}

/*
ArkServiceReverseBoardingAddressOK describes a response with status code 200, with default header values.

A successful response.
*/
type ArkServiceReverseBoardingAddressOK struct {
	Payload *models.V1ReverseBoardingAddressResponse
}

// IsSuccess returns true when this ark service reverse boarding address o k response has a 2xx status code
func (o *ArkServiceReverseBoardingAddressOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ark service reverse boarding address o k response has a 3xx status code
func (o *ArkServiceReverseBoardingAddressOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ark service reverse boarding address o k response has a 4xx status code
func (o *ArkServiceReverseBoardingAddressOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ark service reverse boarding address o k response has a 5xx status code
func (o *ArkServiceReverseBoardingAddressOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ark service reverse boarding address o k response a status code equal to that given
func (o *ArkServiceReverseBoardingAddressOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the ark service reverse boarding address o k response
func (o *ArkServiceReverseBoardingAddressOK) Code() int {
	return 200
}

func (o *ArkServiceReverseBoardingAddressOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/reverseboarding][%d] arkServiceReverseBoardingAddressOK %s", 200, payload)
}

func (o *ArkServiceReverseBoardingAddressOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/reverseboarding][%d] arkServiceReverseBoardingAddressOK %s", 200, payload)
}

func (o *ArkServiceReverseBoardingAddressOK) GetPayload() *models.V1ReverseBoardingAddressResponse {
	return o.Payload
}

func (o *ArkServiceReverseBoardingAddressOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ReverseBoardingAddressResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewArkServiceReverseBoardingAddressDefault creates a ArkServiceReverseBoardingAddressDefault with default headers values
func NewArkServiceReverseBoardingAddressDefault(code int) *ArkServiceReverseBoardingAddressDefault {
	return &ArkServiceReverseBoardingAddressDefault{
		_statusCode: code,
	}
}

/*
ArkServiceReverseBoardingAddressDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ArkServiceReverseBoardingAddressDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this ark service reverse boarding address default response has a 2xx status code
func (o *ArkServiceReverseBoardingAddressDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ark service reverse boarding address default response has a 3xx status code
func (o *ArkServiceReverseBoardingAddressDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ark service reverse boarding address default response has a 4xx status code
func (o *ArkServiceReverseBoardingAddressDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ark service reverse boarding address default response has a 5xx status code
func (o *ArkServiceReverseBoardingAddressDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ark service reverse boarding address default response a status code equal to that given
func (o *ArkServiceReverseBoardingAddressDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the ark service reverse boarding address default response
func (o *ArkServiceReverseBoardingAddressDefault) Code() int {
	return o._statusCode
}

func (o *ArkServiceReverseBoardingAddressDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/reverseboarding][%d] ArkService_ReverseBoardingAddress default %s", o._statusCode, payload)
}

func (o *ArkServiceReverseBoardingAddressDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/reverseboarding][%d] ArkService_ReverseBoardingAddress default %s", o._statusCode, payload)
}

func (o *ArkServiceReverseBoardingAddressDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ArkServiceReverseBoardingAddressDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
