// Code generated by go-swagger; DO NOT EDIT.

package ark_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewArkServiceGetRoundByIDParams creates a new ArkServiceGetRoundByIDParams object
// with the default values initialized.
func NewArkServiceGetRoundByIDParams() *ArkServiceGetRoundByIDParams {
	var ()
	return &ArkServiceGetRoundByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewArkServiceGetRoundByIDParamsWithTimeout creates a new ArkServiceGetRoundByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewArkServiceGetRoundByIDParamsWithTimeout(timeout time.Duration) *ArkServiceGetRoundByIDParams {
	var ()
	return &ArkServiceGetRoundByIDParams{

		timeout: timeout,
	}
}

// NewArkServiceGetRoundByIDParamsWithContext creates a new ArkServiceGetRoundByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewArkServiceGetRoundByIDParamsWithContext(ctx context.Context) *ArkServiceGetRoundByIDParams {
	var ()
	return &ArkServiceGetRoundByIDParams{

		Context: ctx,
	}
}

// NewArkServiceGetRoundByIDParamsWithHTTPClient creates a new ArkServiceGetRoundByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewArkServiceGetRoundByIDParamsWithHTTPClient(client *http.Client) *ArkServiceGetRoundByIDParams {
	var ()
	return &ArkServiceGetRoundByIDParams{
		HTTPClient: client,
	}
}

/*ArkServiceGetRoundByIDParams contains all the parameters to send to the API endpoint
for the ark service get round by Id operation typically these are written to a http.Request
*/
type ArkServiceGetRoundByIDParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the ark service get round by Id params
func (o *ArkServiceGetRoundByIDParams) WithTimeout(timeout time.Duration) *ArkServiceGetRoundByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ark service get round by Id params
func (o *ArkServiceGetRoundByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ark service get round by Id params
func (o *ArkServiceGetRoundByIDParams) WithContext(ctx context.Context) *ArkServiceGetRoundByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ark service get round by Id params
func (o *ArkServiceGetRoundByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ark service get round by Id params
func (o *ArkServiceGetRoundByIDParams) WithHTTPClient(client *http.Client) *ArkServiceGetRoundByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ark service get round by Id params
func (o *ArkServiceGetRoundByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the ark service get round by Id params
func (o *ArkServiceGetRoundByIDParams) WithID(id string) *ArkServiceGetRoundByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the ark service get round by Id params
func (o *ArkServiceGetRoundByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ArkServiceGetRoundByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
