// Code generated by go-swagger; DO NOT EDIT.

package ark_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ark-network/ark/pkg/client-sdk/client/rest/service/models"
)

// NewArkServiceSubmitTxParams creates a new ArkServiceSubmitTxParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewArkServiceSubmitTxParams() *ArkServiceSubmitTxParams {
	return &ArkServiceSubmitTxParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewArkServiceSubmitTxParamsWithTimeout creates a new ArkServiceSubmitTxParams object
// with the ability to set a timeout on a request.
func NewArkServiceSubmitTxParamsWithTimeout(timeout time.Duration) *ArkServiceSubmitTxParams {
	return &ArkServiceSubmitTxParams{
		timeout: timeout,
	}
}

// NewArkServiceSubmitTxParamsWithContext creates a new ArkServiceSubmitTxParams object
// with the ability to set a context for a request.
func NewArkServiceSubmitTxParamsWithContext(ctx context.Context) *ArkServiceSubmitTxParams {
	return &ArkServiceSubmitTxParams{
		Context: ctx,
	}
}

// NewArkServiceSubmitTxParamsWithHTTPClient creates a new ArkServiceSubmitTxParams object
// with the ability to set a custom HTTPClient for a request.
func NewArkServiceSubmitTxParamsWithHTTPClient(client *http.Client) *ArkServiceSubmitTxParams {
	return &ArkServiceSubmitTxParams{
		HTTPClient: client,
	}
}

/*
ArkServiceSubmitTxParams contains all the parameters to send to the API endpoint

	for the ark service submit tx operation.

	Typically these are written to a http.Request.
*/
type ArkServiceSubmitTxParams struct {

	// Body.
	Body *models.V1SubmitTxRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the ark service submit tx params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ArkServiceSubmitTxParams) WithDefaults() *ArkServiceSubmitTxParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the ark service submit tx params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ArkServiceSubmitTxParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the ark service submit tx params
func (o *ArkServiceSubmitTxParams) WithTimeout(timeout time.Duration) *ArkServiceSubmitTxParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ark service submit tx params
func (o *ArkServiceSubmitTxParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ark service submit tx params
func (o *ArkServiceSubmitTxParams) WithContext(ctx context.Context) *ArkServiceSubmitTxParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ark service submit tx params
func (o *ArkServiceSubmitTxParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ark service submit tx params
func (o *ArkServiceSubmitTxParams) WithHTTPClient(client *http.Client) *ArkServiceSubmitTxParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ark service submit tx params
func (o *ArkServiceSubmitTxParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the ark service submit tx params
func (o *ArkServiceSubmitTxParams) WithBody(body *models.V1SubmitTxRequest) *ArkServiceSubmitTxParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the ark service submit tx params
func (o *ArkServiceSubmitTxParams) SetBody(body *models.V1SubmitTxRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ArkServiceSubmitTxParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
