// Code generated by go-swagger; DO NOT EDIT.

package ark_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ark-network/ark/pkg/client-sdk/client/rest/service/models"
)

// ArkServiceSubmitSignedForfeitTransactionsReader is a Reader for the ArkServiceSubmitSignedForfeitTransactions structure.
type ArkServiceSubmitSignedForfeitTransactionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ArkServiceSubmitSignedForfeitTransactionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewArkServiceSubmitSignedForfeitTransactionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewArkServiceSubmitSignedForfeitTransactionsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewArkServiceSubmitSignedForfeitTransactionsOK creates a ArkServiceSubmitSignedForfeitTransactionsOK with default headers values
func NewArkServiceSubmitSignedForfeitTransactionsOK() *ArkServiceSubmitSignedForfeitTransactionsOK {
	return &ArkServiceSubmitSignedForfeitTransactionsOK{}
}

/*
ArkServiceSubmitSignedForfeitTransactionsOK describes a response with status code 200, with default header values.

A successful response.
*/
type ArkServiceSubmitSignedForfeitTransactionsOK struct {
	Payload models.V1SubmitSignedForfeitTransactionsResponse
}

// IsSuccess returns true when this ark service submit signed forfeit transactions o k response has a 2xx status code
func (o *ArkServiceSubmitSignedForfeitTransactionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ark service submit signed forfeit transactions o k response has a 3xx status code
func (o *ArkServiceSubmitSignedForfeitTransactionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ark service submit signed forfeit transactions o k response has a 4xx status code
func (o *ArkServiceSubmitSignedForfeitTransactionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ark service submit signed forfeit transactions o k response has a 5xx status code
func (o *ArkServiceSubmitSignedForfeitTransactionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ark service submit signed forfeit transactions o k response a status code equal to that given
func (o *ArkServiceSubmitSignedForfeitTransactionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the ark service submit signed forfeit transactions o k response
func (o *ArkServiceSubmitSignedForfeitTransactionsOK) Code() int {
	return 200
}

func (o *ArkServiceSubmitSignedForfeitTransactionsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/round/submitForfeitTxs][%d] arkServiceSubmitSignedForfeitTransactionsOK %s", 200, payload)
}

func (o *ArkServiceSubmitSignedForfeitTransactionsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/round/submitForfeitTxs][%d] arkServiceSubmitSignedForfeitTransactionsOK %s", 200, payload)
}

func (o *ArkServiceSubmitSignedForfeitTransactionsOK) GetPayload() models.V1SubmitSignedForfeitTransactionsResponse {
	return o.Payload
}

func (o *ArkServiceSubmitSignedForfeitTransactionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewArkServiceSubmitSignedForfeitTransactionsDefault creates a ArkServiceSubmitSignedForfeitTransactionsDefault with default headers values
func NewArkServiceSubmitSignedForfeitTransactionsDefault(code int) *ArkServiceSubmitSignedForfeitTransactionsDefault {
	return &ArkServiceSubmitSignedForfeitTransactionsDefault{
		_statusCode: code,
	}
}

/*
ArkServiceSubmitSignedForfeitTransactionsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ArkServiceSubmitSignedForfeitTransactionsDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this ark service submit signed forfeit transactions default response has a 2xx status code
func (o *ArkServiceSubmitSignedForfeitTransactionsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ark service submit signed forfeit transactions default response has a 3xx status code
func (o *ArkServiceSubmitSignedForfeitTransactionsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ark service submit signed forfeit transactions default response has a 4xx status code
func (o *ArkServiceSubmitSignedForfeitTransactionsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ark service submit signed forfeit transactions default response has a 5xx status code
func (o *ArkServiceSubmitSignedForfeitTransactionsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ark service submit signed forfeit transactions default response a status code equal to that given
func (o *ArkServiceSubmitSignedForfeitTransactionsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the ark service submit signed forfeit transactions default response
func (o *ArkServiceSubmitSignedForfeitTransactionsDefault) Code() int {
	return o._statusCode
}

func (o *ArkServiceSubmitSignedForfeitTransactionsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/round/submitForfeitTxs][%d] ArkService_SubmitSignedForfeitTransactions default %s", o._statusCode, payload)
}

func (o *ArkServiceSubmitSignedForfeitTransactionsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/round/submitForfeitTxs][%d] ArkService_SubmitSignedForfeitTransactions default %s", o._statusCode, payload)
}

func (o *ArkServiceSubmitSignedForfeitTransactionsDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ArkServiceSubmitSignedForfeitTransactionsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
