// Code generated by go-swagger; DO NOT EDIT.

package ark_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ark-network/ark/pkg/client-sdk/client/rest/service/models"
)

// NewArkServiceSendTreeNoncesParams creates a new ArkServiceSendTreeNoncesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewArkServiceSendTreeNoncesParams() *ArkServiceSendTreeNoncesParams {
	return &ArkServiceSendTreeNoncesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewArkServiceSendTreeNoncesParamsWithTimeout creates a new ArkServiceSendTreeNoncesParams object
// with the ability to set a timeout on a request.
func NewArkServiceSendTreeNoncesParamsWithTimeout(timeout time.Duration) *ArkServiceSendTreeNoncesParams {
	return &ArkServiceSendTreeNoncesParams{
		timeout: timeout,
	}
}

// NewArkServiceSendTreeNoncesParamsWithContext creates a new ArkServiceSendTreeNoncesParams object
// with the ability to set a context for a request.
func NewArkServiceSendTreeNoncesParamsWithContext(ctx context.Context) *ArkServiceSendTreeNoncesParams {
	return &ArkServiceSendTreeNoncesParams{
		Context: ctx,
	}
}

// NewArkServiceSendTreeNoncesParamsWithHTTPClient creates a new ArkServiceSendTreeNoncesParams object
// with the ability to set a custom HTTPClient for a request.
func NewArkServiceSendTreeNoncesParamsWithHTTPClient(client *http.Client) *ArkServiceSendTreeNoncesParams {
	return &ArkServiceSendTreeNoncesParams{
		HTTPClient: client,
	}
}

/*
ArkServiceSendTreeNoncesParams contains all the parameters to send to the API endpoint

	for the ark service send tree nonces operation.

	Typically these are written to a http.Request.
*/
type ArkServiceSendTreeNoncesParams struct {

	// Body.
	Body *models.V1SendTreeNoncesRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the ark service send tree nonces params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ArkServiceSendTreeNoncesParams) WithDefaults() *ArkServiceSendTreeNoncesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the ark service send tree nonces params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ArkServiceSendTreeNoncesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the ark service send tree nonces params
func (o *ArkServiceSendTreeNoncesParams) WithTimeout(timeout time.Duration) *ArkServiceSendTreeNoncesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ark service send tree nonces params
func (o *ArkServiceSendTreeNoncesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ark service send tree nonces params
func (o *ArkServiceSendTreeNoncesParams) WithContext(ctx context.Context) *ArkServiceSendTreeNoncesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ark service send tree nonces params
func (o *ArkServiceSendTreeNoncesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ark service send tree nonces params
func (o *ArkServiceSendTreeNoncesParams) WithHTTPClient(client *http.Client) *ArkServiceSendTreeNoncesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ark service send tree nonces params
func (o *ArkServiceSendTreeNoncesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the ark service send tree nonces params
func (o *ArkServiceSendTreeNoncesParams) WithBody(body *models.V1SendTreeNoncesRequest) *ArkServiceSendTreeNoncesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the ark service send tree nonces params
func (o *ArkServiceSendTreeNoncesParams) SetBody(body *models.V1SendTreeNoncesRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ArkServiceSendTreeNoncesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
