// Code generated by go-swagger; DO NOT EDIT.

package ark_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ark-network/ark/pkg/client-sdk/client/rest/service/models"
)

// ArkServiceConfirmRegistrationReader is a Reader for the ArkServiceConfirmRegistration structure.
type ArkServiceConfirmRegistrationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ArkServiceConfirmRegistrationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewArkServiceConfirmRegistrationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewArkServiceConfirmRegistrationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewArkServiceConfirmRegistrationOK creates a ArkServiceConfirmRegistrationOK with default headers values
func NewArkServiceConfirmRegistrationOK() *ArkServiceConfirmRegistrationOK {
	return &ArkServiceConfirmRegistrationOK{}
}

/*
ArkServiceConfirmRegistrationOK describes a response with status code 200, with default header values.

A successful response.
*/
type ArkServiceConfirmRegistrationOK struct {
	Payload models.V1ConfirmRegistrationResponse
}

// IsSuccess returns true when this ark service confirm registration o k response has a 2xx status code
func (o *ArkServiceConfirmRegistrationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ark service confirm registration o k response has a 3xx status code
func (o *ArkServiceConfirmRegistrationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ark service confirm registration o k response has a 4xx status code
func (o *ArkServiceConfirmRegistrationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this ark service confirm registration o k response has a 5xx status code
func (o *ArkServiceConfirmRegistrationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this ark service confirm registration o k response a status code equal to that given
func (o *ArkServiceConfirmRegistrationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the ark service confirm registration o k response
func (o *ArkServiceConfirmRegistrationOK) Code() int {
	return 200
}

func (o *ArkServiceConfirmRegistrationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/batch/ack][%d] arkServiceConfirmRegistrationOK %s", 200, payload)
}

func (o *ArkServiceConfirmRegistrationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/batch/ack][%d] arkServiceConfirmRegistrationOK %s", 200, payload)
}

func (o *ArkServiceConfirmRegistrationOK) GetPayload() models.V1ConfirmRegistrationResponse {
	return o.Payload
}

func (o *ArkServiceConfirmRegistrationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewArkServiceConfirmRegistrationDefault creates a ArkServiceConfirmRegistrationDefault with default headers values
func NewArkServiceConfirmRegistrationDefault(code int) *ArkServiceConfirmRegistrationDefault {
	return &ArkServiceConfirmRegistrationDefault{
		_statusCode: code,
	}
}

/*
ArkServiceConfirmRegistrationDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ArkServiceConfirmRegistrationDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this ark service confirm registration default response has a 2xx status code
func (o *ArkServiceConfirmRegistrationDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ark service confirm registration default response has a 3xx status code
func (o *ArkServiceConfirmRegistrationDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ark service confirm registration default response has a 4xx status code
func (o *ArkServiceConfirmRegistrationDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ark service confirm registration default response has a 5xx status code
func (o *ArkServiceConfirmRegistrationDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ark service confirm registration default response a status code equal to that given
func (o *ArkServiceConfirmRegistrationDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the ark service confirm registration default response
func (o *ArkServiceConfirmRegistrationDefault) Code() int {
	return o._statusCode
}

func (o *ArkServiceConfirmRegistrationDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/batch/ack][%d] ArkService_ConfirmRegistration default %s", o._statusCode, payload)
}

func (o *ArkServiceConfirmRegistrationDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/batch/ack][%d] ArkService_ConfirmRegistration default %s", o._statusCode, payload)
}

func (o *ArkServiceConfirmRegistrationDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ArkServiceConfirmRegistrationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
