name: ci_integration

on:
  push:
    branches: 
      - master
    paths:
      - "server/**"

jobs:
  test:
    name: integration tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ">1.17.2"
      - uses: actions/checkout@v3
      - run: go get -v -t -d ./...
      - name: integration testing
        run: make integrationtest
  