name: API Spec Changes

on:
  push:
    paths:
      - 'api-spec/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: bufbuild/buf-setup-action@v1.3.1
      
      - name: check proto linting
        run: buf lint